kunai-project/kunai

Cargo.lock, kunai/Cargo.toml, kunai/src/bin/main.rs
- update gene
- fix ancestor resolution
- handle stdin events in kunai replay command
=> Fix and enhancements

kunai-common/src/bpf_events/user.rs, kunai-common/src/buffer.rs, kunai-common/src/buffer/bpf.rs, kunai-common/src/co_re.rs, kunai-common/src/co_re/c/shim.c, kunai-common/src/co_re/core_iov.rs, kunai-common/src/co_re/core_page.rs, kunai-common/src/co_re/gen.rs, kunai-ebpf/src/probes.rs, kunai-ebpf/src/probes/fs.rs, kunai-ebpf/src/probes/mprotect.rs, kunai-ebpf/src/probes/prctl.rs, kunai-ebpf/src/probes/send_data.rs, kunai/src/bin/main.rs, kunai/src/info.rs, kunai/src/util.rs
- userland now fully backed by tokio.rs
- early return in high throughput probes when events are disabled -> perf improvement in user and kernel
- filling Buffer from `struct bio_vec` is now possible -> improves `send_data` probe coverage
=> Enhancements

kunai-common/src/bpf_events/user.rs, kunai/src/bin/main.rs
This PR improves the way eBPF events are processed:
- algorithm is simpler
- code is better segmented
- a dedicated tokio task is spawned to process piped event
- debug assertions to verify events arrive in order on consumer side
The outcome if this PR is a x2 processing speed.
=> enhance: faster EventProducer implementation

kunai/src/bin/main.rs, kunai/src/lib.rs, kunai/src/tests/kernel.rs
This PR aims at removing code duplicates in test.rs and main.rs
=> refactor(user): moved bpf loading in library

kunai/src/bin/main.rs, kunai/src/config.rs
Add a command line option to install kunai:
1. install the binary
2. install a configuration file
3. choose a place for log files
4. possibility to create and enable a systemd unit
=> feat: install CLI command

Cargo.lock, kunai/Cargo.toml
=> fix: update yara-x

kunai/src/bin/main.rs
=> fix(main): check if another kunai instance is running

kunai/src/bin/main.rs
Fix missing implementation for replaying `kill_event`
=> fix(main): kill_event not implement in replay command

kunai/src/bin/main.rs, kunai/src/config.rs
Add checks to prevent a hardened installation if kernel does not support it
=> feat: install in harden mode

Cargo.lock, kunai/src/bin/main.rs
there is a bug in kill action that can lead kunai to kill itself -_-
=> fix(main): kill bug

kunai/src/bin/main.rs
there was a bug showing **all** file_scans when `always_show_positive_scans` option was set
=> fix(main): show only positive scans

kunai/src/bin/main.rs, kunai/src/cache.rs, kunai/src/events.rs
There were some inconsistencies in events, sometimes a path field was named `file`. For sake of simplicity everything has been renamed to `path`
=> fix(user): normalize file -> path

README.md
Fix broken events url in README.md
=> Fix broken events url in README.md

kunai/src/bin/main.rs, kunai/src/config.rs
- group scanner related configuration
- add `min_severity` field to configure minimal severity to display events with detection
- CLI switch to configure `min_severity`
- rename `always_show_positive_scans` with `show_positive_file_scan`
=> rework(user): configuration

Cargo.lock, kunai/Cargo.toml, kunai/src/bin/main.rs, kunai/src/config.rs
This PR addresses the need to have unbuffered kunai output for real-time event retrieval/processing needs.
Feature motivated by discussion: https://discord.com/channels/1121081818154815488/1121081818154815491/1309514408610758706
=> Feat unbuffered output

kunai/src/bin/main.rs, kunai/src/cache.rs, kunai/src/util/account.rs, kunai/src/util/namespace.rs
- bug for some sandboxing solutions not exposing /etc/passwd /etc/groups
=> fix: user/group name resolution

Cargo.lock, Cargo.toml, kunai-ebpf/Cargo.toml, kunai/Cargo.toml, kunai/src/bin/main.rs
This PR introduces a new feature allowing to test kunai rules.
The overall idea of rule testing is being able to verify kunai rule in a CI/CD pipeline so that we are always sure rules are:
1. detecting what they aim at detecting
2. do not generate obvious false positives
This will be particularly useful for any contribution to https://github.com/kunai-project/community-rules
=> feat: rule testing

kunai/src/bin/main.rs, kunai/src/util.rs
There is an issue when running as a service on older kernels where `RLIMIT_MEMLOCK` occurs in the first place.
The solution of fixing limit in `securityfs` works at the only condition that the fs is mounted prior kunai starts. If is this not the case kunai will fail to start. To fix this we need to set `RLIMIT_MEMLOCK` in Kunai itself and this is what this PR is doing.
=> Fix rlimit memlock

kunai-common/src/buffer/bpf.rs
=> fix: aarch64 verifier kicking

.github/workflows/ci.yml, .github/workflows/kernel-tracker.yml, scripts/ci/test_kernel.sh
This PR implements aarch64 loading tests to detect issues like: #179
The tests are cross-compiled and run in qemu.
cc: @Shoyo-08
=> add(ci): aarch64 test case

kunai/src/bin/main.rs, kunai/src/compat.rs, kunai/src/events/agent.rs, kunai/src/tests/kernel.rs, kunai/src/util.rs
Code review around `unwrap` calls done following issue #178
=> refactor: several unwrap calls

kunai/src/bin/main.rs
This PR addresses an issue raised in #190: the need to have a way to validate a configuration file. The way to validate a configuration file is `kunai config --validate /path/to/config.yaml`. This initializes tries to initialize kunai with the configuration file and then quits with appropriate error code (0 on success and 1 on error).
=> feat: validate config file

Cargo.lock, kunai/Cargo.toml, kunai/src/bin/main.rs, kunai/src/containers.rs, kunai/src/events.rs, rust-toolchain.toml
Use the latest gene version increasing scan throughput
=> perf: increase scan speed
