Cargo.lock
kunai/Cargo.toml
kunai/src/bin/main.rs

When nested tokio tasks panic they don't panic kunai. This is an expected behavior by tokio yet we need to address this issue not to hang the application in case of bug. To do that we need to bubble up task errors and eventually panic in main tokio task.

issue when tokio task panic

---

.cargo/config.toml
Cargo.lock
Cargo.toml
kunai-common/src/bpf_events.rs
kunai-common/src/bpf_events/events.rs
kunai-common/src/time.rs
kunai-ebpf/.cargo/config.toml
kunai-ebpf/Cargo.toml
kunai/.cargo/config.toml
kunai/Cargo.toml
kunai/src/bin/main.rs
kunai/src/cache.rs
kunai/src/config.rs
kunai/src/events.rs
kunai/src/lib.rs
kunai/src/util.rs
kunai/src/util/defer.rs
kunai/src/yara.rs
scripts/ci/test_kernel.sh
xtask/src/ebpf.rs
xtask/src/main.rs
xtask/src/user.rs
xtask/src/utils.rs

This PR contains the first implementation of action (defined in detection rules) handling.
It also includes all the work concerning [yara-x](https://virustotal.github.io/yara-x/) integration.
For the moment only two actions are supported and implemented in this PR:
- Kill process via `kill` action keyword
- Scan a file via `scan-files` action keyword
Here are a couple of implementation details. 
- When a file is scanned a dedicated event (named `file_scan`) containing file metadata and signatures will be generated
- If the yara engine contains no rule, only metadata will be populated in the event
- Once generated a `file_scan` event will make a trip into the Kunai events scanning engine. This makes possible any classical filter/detection rule to match on `file_scan`. So thanks to this it …

feat: implement handling action in detection rules

---

kunai/src/bin/main.rs
kunai/src/ioc.rs

The new IoC format needs to contain a `severity` field. In this way, anyone is free to define the severity of an IoC based on its own criteria.
```json
{
"uuid": "ce473a0c-acf3-497b-bf35-cf534a1b69fa",
"source": "CIRCL OSINT Feed",
"value": "3proxy.ru",
"event_uuid": "d67bfbe0-e01d-4e2e-8a56-214805d85aee",
"severity": 7
}
```
Notes: 
- `severity` field is mandatory
- if the same IoC (by value) appears several times in the configuration file only the maximum severity will be kept 
- the script in kunai tools repository will be updated to ship IoCs with default severity

fix #70: making IoC severity configurable

---

Cargo.lock
kunai-common/src/bpf_events/events/connect.rs
kunai-common/src/bpf_events/events/dns_query.rs
kunai-common/src/bpf_events/events/send_entropy.rs
kunai-common/src/co_re/c/shim.c
kunai-common/src/co_re/core_sock.rs
kunai-common/src/co_re/gen.rs
kunai-common/src/net.rs
kunai-common/src/net/bpf.rs
kunai-common/src/net/user.rs
kunai-ebpf/src/probes/connect.rs
kunai-ebpf/src/probes/dns.rs
kunai-ebpf/src/probes/send_data.rs
kunai/Cargo.toml
kunai/src/bin/main.rs
kunai/src/events.rs
kunai/src/util.rs

This PR aims at integrating community-id ( https://github.com/corelight/community-id-spec) into some of the kunai logs:
This feature is valuable on the following aspects:
- it allows to correlate kunai log with external log/alert sources such as IDS or traffic analysis tools
- given a community-id from an external source and thanks to the task UUIDs used in kunai it is possible to find the exact root (application, parents and all ancestors) of such traffic.
Fields of applications:
- Incident Response
- Threat-Hunting
- Network alert investigation
- Understand which application generate which traffic
Limitations:
- NAT traffic (often used in Linux containers) won't produce community-id that can be correlated with traffic analysis tools

feat: integrate community-id

---

.github/workflows/kernel-tracker.yml

Optimize kernel-tracker.yml by not always cloning full linux kernel repo

fix(workflow): optimize kernel-tracker.yml

---

Cargo.lock
kunai/Cargo.toml
kunai/src/bin/main.rs

This PR add a new feature simplifying detection/filtering rule writing. It allows specifying events to filter by their names instead of event id.
```yaml
name: log.mprotect_exec
params:
filter: true
match-on:
events:
kunai:
- mprotect_exec
```
```yaml
name: exclude.mprotect_exec
params:
filter: true
match-on:
events:
kunai:
- -mprotect_exec
```

feat: filter by event name in rules

---

kunai-common/src/bpf_events.rs
kunai-common/src/config.rs
kunai/src/bin/main.rs

Minor changes in event processing:
- moved `execve`, `execve_script` and `clone` filtering in consumer as those are needed for correlation
- `task_sched` events are no longer filterable as they are needed for correlation

fix: event processing

---

kunai/src/cache.rs
kunai/src/events.rs

fix: display error field in FileMeta and in FileScanData

---

Cargo.lock
kunai-common/Cargo.toml
kunai-common/src/bpf_events/user.rs
kunai/Cargo.toml
kunai/src/bin/main.rs
kunai/src/config.rs

Changes configuration file format from `toml` to `yaml` prevents having several file format to support and to know (for end-user).
This PR also modifies the structure used to store event configuration. It got switched from `Vec` to `BTreeMap` (to keep events ordered)

chg: config format

---

kunai/src/bin/main.rs

Kunai stores last logs in plain text but compresses old archives. It can be a burden to read the logs in the proper order for inspection. So this PR adds a new command in the CLI to read the logs and print them out (in good order) in the terminal.

feat(user): add a logs command in CLI

---

Cargo.lock
kunai/src/bin/main.rs

Support arbitrary file extension for rule/ioc files when these are configured by file only.

fix(main): arbitrary ext ioc/rule file loading

---

kunai-common/src/bpf_events.rs
kunai-common/src/bpf_events/events.rs
kunai-common/src/bpf_events/events/ptrace.rs
kunai-ebpf/src/probes.rs
kunai-ebpf/src/probes/ptrace.rs
kunai/src/bin/main.rs
kunai/src/events.rs

Generate a kunai event when a process issues a ptrace syscall.
NB: so far the events fires up only when PTRACE_MODE_ATTACH: https://elixir.bootlin.com/linux/v6.11.5/source/include/linux/ptrace.h#L63

feat: new ptrace security event

---

Cargo.lock
Cargo.toml
kunai-common/src/bpf_events.rs
kunai-ebpf/Cargo.toml
kunai/src/bin/main.rs
kunai/src/events.rs
kunai/src/info.rs

For zombie processes `ancestors` and `parent_exe` were not the "real" ones.
The purpose of making a zombie process is making difficult to track the real **parent/child** relationship. However in kunai we have the data to recover the real **parent/child** relationships across the full chains of ancestors of a given process.
**Prior to this PR**: kunai is computing `ancestors` and `parent_exe` from the `parent_task` returned by the kernel. The drawback with this approach is that when the process becomes a zombie the kernel sets `parent` to **init process** and we lose track of the real origin of the process.
**This PR** addresses this issue and puts the real `ancestors` and real `parent_exe` in events' fields
Using real `ancestors` and `parent_exe` introduces some inconsistencies in the …

fix: ancestors and parent_exe for zombie process

---

kunai-common/src/bpf_events.rs
kunai-common/src/bpf_events/events.rs
kunai-common/src/co_re/c/shim.c
kunai-common/src/co_re/core_fs.rs
kunai-common/src/co_re/gen.rs
kunai-ebpf/src/probes/fs.rs
kunai/src/bin/main.rs

New event generated on file creation

feat: file create event

---

kunai-common/src/co_re/c/shim.c
kunai-common/src/co_re/core_fs.rs
kunai-common/src/co_re/gen.rs
kunai-common/src/config.rs
kunai-common/src/path.rs
kunai-common/src/path/bpf.rs
kunai-ebpf/src/probes/fs.rs
kunai/src/bin/main.rs
kunai/src/config.rs
kunai/src/util.rs

This PR addresses the need to throttle I/O events to prevent event loss, which can disrupt Kunai's eBPF-based correlation mechanisms.
Event loss is problematic because Kunai relies on eBPF events to allocate and free structures used for correlation. Missing crucial events may lead to incomplete correlations or memory leaks.
I/O events, being among the fastest, can easily generate tens of thousands of events per second, quickly saturating the event buffer.
To mitigate event loss, this PR introduces the following filtering mechanisms:
- **De-duplication of `write_close` events**: Prevents redundant events from overwhelming the buffer.
- **Per-task I/O throttling**: Limits I/O events on a per-task basis, ensuring that excessive I/O from one task doesn't affect others.
- **Global I/O …

feat: limit i/o related events

---

kunai-common/src/bpf_events.rs
kunai-common/src/bpf_events/events.rs
kunai-common/src/bpf_events/events/error.rs
kunai-ebpf/src/probes/fs.rs
kunai/src/bin/main.rs
kunai/src/events.rs

Introduces a new **error** event servicing the following purposes:
- easily bubbling up important errors (in case of log collection)
- being able to filter errors and take actions if necessary

feat: error event

---

kunai/src/bin/main.rs

User/group namespace error logs were too verbose in case of resolution failure as it was generated for every single event. Those got turned to debug log level so that user can turn this on only if needed.

fix: verbose error log

---

Cargo.lock
kunai-common/src/bpf_events.rs
kunai-common/src/bpf_events/events.rs
kunai-common/src/bpf_events/events/status.rs
kunai/Cargo.toml
kunai/src/bin/main.rs
kunai/src/config.rs
kunai/src/events.rs
kunai/src/events/start.rs
kunai/src/util.rs
kunai/src/util/uptime.rs

This PR introduces a new `start` event containing system and kunai information when the tool is started:
This event can be used (amongst other things) to:
- detect when the service is started / restarted
- track configuration changes
- know from logs the kunai version and cryptographic hash of the binary
fix #9

feat: new start event

---

kunai-ebpf/src/probes/execve.rs

This PR attempts at fixing a rare error happening in `execve` probe (see #159)
The occurence of this error seems pretty random, so it is impossible to replicate (so far).
Thus some code review has been done on the probe and we fix possible cause of this error:
- the probe uses two maps of different sizes, that may cause data to be missing in one of them -> fix: put the same size for both the maps
- proper cleanup of both the maps

fix: attempt execve rare error

---

Cargo.lock
kunai-common/Cargo.toml
kunai-common/src/buffer/bpf.rs
kunai-common/src/co_re/gen.rs
kunai-common/src/lib.rs
kunai-ebpf/rust-toolchain.toml
kunai-ebpf/src/main.rs

Rust toolchain upgrade and fixes.
This upgrade caused one probe to fail (probably due to new compilation/optimization decisions). So we needed to change a bit the logic of `iov` and `biovec` reading.

chore: ebpf toolchain upgrade

---

kunai-common/src/path.rs
kunai-common/src/string.rs
kunai-common/src/utils.rs

replace `bound_value_for_verifier` and `cap_size` functions by `clamp` methods

refactor(ebpf): replace fn calls by clamp

---

kunai-common/src/config.rs

Event filter was not working as intented, especially for non-configurable events. Those were filtered out by the current design of the Filter structure.
Thy PR fixes this by considering as enabled any event which is not configurable.

fix: event filter

---

kunai-common/src/net/bpf.rs
kunai-ebpf/src/probes/dns.rs

An issue with dns_query events has been raised on X: https://x.com/cr0nym/status/1879520129303838895
After investigations, this is due to the way the APIs used in the payload work. Using sendto and recvfrom calls do not set IP/port information in the sock kernel structure. As we are looking at this structure to establish whether the connection looks like DNS, we missed those. 
* A fix for that issue has  been made in this PR
* It also contains a fix to correct the `src` port which was not in the good endianness

fix: dns probe

---

.cargo/config.toml
Cargo.lock
Cargo.toml
xlaunch/Cargo.toml
xlaunch/src/main.rs
xtask/.cargo/config.toml

Currently cargo alias are hardcoding the target which is not very portable.
The goal of this PR is to make cargo xtask commands cross architectures.
For the moment two architectures are supported x86_64 and aarch64

create: xlaunch cross arch xtask launcher

---

kunai-common/src/co_re/c/shim.c
kunai-common/src/co_re/core_fs.rs
kunai-common/src/co_re/gen.rs

This is due to a change in the MAC time is stored in `inode` structure.
Instead of a `timespec64` those are now two separate members of the struct. 
See https://elixir.bootlin.com/linux/v6.11/source/include/linux/fs.h#L668 for further details.

This PR fixes a compatibility issue with kernels >= 6.11

---

kunai-common/src/buffer/user.rs
kunai/src/bin/main.rs

Attempts at fixing: #193 
Kunai crashes attempting to parse non-utf8 code points in some process command lines. Instead of relying on `unwrap`  the `to_argv` function has been changed so that it both returns the argv (in a vec) and the latest decoding error. Instead of panicking Kunai now prints the error message (if any) in the logs. The default behavior is also to use the parsed argv containing arguments which could be decoded without errors.

fix: kunai utf8 decoding crash

---

Cargo.lock
kunai/Cargo.toml
kunai/src/bin/main.rs
kunai/src/events.rs

This PR add visibility on the filter matching an event, useful for:
- testing / debugging filters (see https://github.com/kunai-project/kunai/issues/190#issuecomment-2800110241)
- showing context about filters (through tags)
This feature required some modifications of the ScanResult structure as we needed to separate filter and detection matches.

feat: filter info

---

kunai/src/bin/main.rs
kunai/src/events.rs

Hi, I added **parent_command_line** because parent arguments are very important within a single event when writing rules in a large number of cases. This field allows you to avoid writing complex sequence rules and write rules for detecting malicious activity within one event.
Example: In this case we can reliably track Interactive Terminal Spawned via Python. 
Executed bash via python using subprocess.
```json
{
"data": {
"ancestors": "/usr/lib/systemd/systemd|/usr/lib/systemd/systemd|/usr/bin/konsole|/usr/bin/zsh|/usr/bin/python3.13",
"parent_exe": "/usr/bin/python3.13",
"parent_command_line": "python3 -c \"import subprocess; subprocess.run('bash')\"",
"command_line": "bash",
"exe": {
"path": "/usr/bin/bash",
"md5": "af00f880da2e5211cbb988e18a726685",
"sha1": …
```

feat: add parent_command_line for execve and execve_script

---

kunai-common/src/bpf_events/events/bpf.rs
kunai-common/src/bpf_events/events/correlation.rs
kunai-common/src/bpf_events/events/send_entropy.rs
kunai-common/src/bpf_events/user.rs
kunai/src/bin/main.rs

This PR refactor the way eBPF events are treated in userland.
Motivation:
- code heavily relying on macros
- code could be simplified by the use of an enum
A side effect of this refactor is a **15% event throughput increase** due to the code simplifications.
This refactoring activity lead to the discovery of: #205

refactor: EncodedEvent to EbpfEvent enum
